### ISSUE TITLE
[intermittent] Exception caught by Mina when queue subscriber closes while receiving messages.

### ISSUE THREAD

**Issue by MaryamZi** [wso2/carbon-business-messaging#509]
Steps to reproduce :

1. Start two mb nodes (nodeA (coordinator) , nodeB) with clustering enabled.
2. Using jms client subscribe to queue "MyQueue" in nodeB.
3. Send 100,000 queue messages to "MyQueue" to nodeB.
4. Close subscriber while receiving messages.
5. Following error message appears on mb node. (even though this error appears, after subscriber comes online again, it will receive all missed queue messages)

[2015-03-11 12:07:27,553] ERROR {org.wso2.andes.transport.network.mina.MinaNetworkHandler} -  Exception caught by Mina
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor.read(SocketIoProcessor.java:218)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor.process(SocketIoProcessor.java:198)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor.access$400(SocketIoProcessor.java:45)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor$Worker.run(SocketIoProcessor.java:485)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51)
	at java.lang.Thread.run(Thread.java:745)
[2015-03-11 12:07:27,555] ERROR {org.wso2.andes.server.protocol.AMQProtocolEngine} -  IOException caught in/10.100.101.9:52728(admin), session closed implictly: java.io.IOException: Connection reset by peer
[2015-03-11 12:07:27,555] ERROR {org.wso2.andes.transport.network.mina.MinaNetworkHandler} -  Exception caught by Mina
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor.doFlush(SocketIoProcessor.java:414)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor.doFlush(SocketIoProcessor.java:332)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor.access$500(SocketIoProcessor.java:45)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor$Worker.run(SocketIoProcessor.java:488)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51)
	at java.lang.Thread.run(Thread.java:745)
[2015-03-11 12:07:27,555] ERROR {org.wso2.andes.server.protocol.AMQProtocolEngine} -  IOException caught in/10.100.101.9:52728(admin), session closed implictly: java.io.IOException: Broken pipe

From: https://wso2.org/jira/browse/MB-982

**Comment by zhangyl45** [comment]
did you fix this issue?
